repos:
  # a list of available plugins is here:
  # https://pre-commit.com/hooks.html

  # black: python code linting
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3

  # Javascript linting
  - repo: https://github.com/prettier/prettier
    rev: 2.0.4
    hooks:
      - id: prettier

  # various code cleanup tasks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-merge-conflict
      - id: detect-aws-credentials
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  # python import sorting, remove unused imports
  - repo: https://github.com/sqlalchemyorg/zimports/
    rev: 0.2.0
    hooks:
      - id: zimports

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.22.0
    hooks:
      - id: markdownlint

  # commit message linting
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.13.1
    hooks:
      - id: gitlint
