repos:
  # a list of available plugins is here:
  # https://pre-commit.com/hooks.html

  # black: python code linting
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3

  # Javascript linting
  - repo: https://github.com/prettier/prettier
    rev: 2.0.4
    hooks:
      - id: prettier

  # standard cleanup tasks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-merge-conflict
      - id: detect-aws-credentials
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: pretty-format-json
      - id: check-executables-have-shebangs

  # python import sorting, remove unused imports
  - repo: https://github.com/sqlalchemyorg/zimports/
    rev: 0.2.0
    hooks:
      - id: zimports

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.22.0
    hooks:
      - id: markdownlint

  # Dockerfile linting
  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint

  # HTML linting
  - repo: https://github.com/Lucas-C/pre-commit-hooks-java
    sha: 1.3.9
    hooks:
      - id: validate-html
        args: [--remove-mustaches, --mustache-remover=jinja2]

  # Security: static code analysis
  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        args: [-x, tests]

  # Security: dependency vulnerability check
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    sha: v1.1.0
    hooks:
      - id: python-safety-dependencies-check
